In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch

In [2]:
print(torch.__version__)

2.10.0+cpu


Introduction to tensors


In [3]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [ ]:
matrix=torch.tensor([[7,8],
                     [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix[1]

tensor([ 9, 10])

In [11]:
Tensor=torch.tensor([[[1,2,3],
                      [1,6,9],
                      [2,4,5]]])
Tensor

tensor([[[1, 2, 3],
         [1, 6, 9],
         [2, 4, 5]]])

In [16]:
Tensor.ndim

2

In [22]:
Tensor.shape

torch.Size([1, 3, 3])

Random tensor


In [19]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.8317, 0.3379, 0.1215, 0.1096],
        [0.0969, 0.1498, 0.1859, 0.5964],
        [0.8815, 0.7957, 0.8380, 0.2170]])

In [14]:
random_tensor.shape

torch.Size([3, 4])

In [20]:
#create a random tensor with similar shape to an image tensor
random_image_tensor=torch.rand(size=(224,224,3))
random_image_tensor.shape,random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and ones

In [21]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Range of Tensors

In [23]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([  1, 100, 199, 298, 397, 496, 595, 694, 793, 892, 991])

In [26]:
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor dataTypes

In [ ]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)

In [31]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

Tensor attributes

In [32]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.3243, 0.6665, 0.9558, 0.4202],
        [0.9159, 0.9523, 0.7530, 0.7400],
        [0.8672, 0.3852, 0.4767, 0.3130]])

In [35]:
print(some_tensor)
print(f"datatype of tensor:{some_tensor.dtype}")
print(f"shape of tensor:{some_tensor.shape}")
print(f"device tensor is on:{some_tensor.device}")

tensor([[0.3243, 0.6665, 0.9558, 0.4202],
        [0.9159, 0.9523, 0.7530, 0.7400],
        [0.8672, 0.3852, 0.4767, 0.3130]])
datatype of tensor:torch.float32
shape of tensor:torch.Size([3, 4])
device tensor is on:cpu


Manipulating Tensor

In [36]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [48]:
tensor=tensor*10
tensor

tensor([1., 2., 3.])

In [50]:
tensor=torch.tensor([1,2,3])
torch.mul(tensor,10)

tensor([10, 20, 30])

Matrix Multiplication

In [51]:
print(tensor*tensor)

tensor([1, 4, 9])


In [52]:
torch.matmul(tensor,tensor)

tensor(14)

In [56]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 15.6 ms
Wall time: 0 ns


tensor(14)

In [68]:
%%time
value=0
for i in range(len(tensor)):
    value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 7.54 ms


Shape Errors

In [69]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.1428, 0.2431, 0.8629],
        [0.1403, 0.2675, 0.9294],
        [0.2473, 0.1109, 0.6114]])

In [75]:
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_B=torch.tensor([[7,8],
                       [9,10],
                       [11,12]])


In [76]:
tensor_B.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [77]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])