In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch

Mean,max,min,sum etc


In [2]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [3]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [4]:
torch.max(x)

tensor(90)

In [5]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [6]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [7]:
x.argmin()

tensor(0)

In [8]:
x.argmax()

tensor(9)

Reshaping,stacking,squeezing and unsqeezing tensors

In [9]:
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [10]:
x_reshaped=x.reshape(1,9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [11]:
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#changing z changes x(because view of a tensor shares the same memory as the orginial input)
z[:,0]=5
z,x    

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [13]:
#stack tensors on top of each other
x_stack=torch.stack([x,x,x,x])
x_stack

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [14]:
#torch squeeze().removes all single dimensions from a target tensor
print(f"previous tensor:{x_reshaped}")
print(f"previous shape :{x_reshaped.shape}")
x_reshaped.shape

previous tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous shape :torch.Size([1, 9])


torch.Size([1, 9])

In [15]:
x_sequeezes=x_reshaped.squeeze()
print(f"new tensor:{x_sequeezes}")

new tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


In [18]:
#torch unsqueeze()-adds a single dimension to a target tensor at a specific dim
print(f"previous target:{x_sequeezes}")
print(f"previous shape :{x_sequeezes.shape}")

#add an extra dimension with unsqeeze
x_unsequeezed=x_sequeezes.unsqueeze(dim=0)
print(f"new tensor:{x_unsequeezed}")
print(f"new shape:{x_unsequeezed.shape}")

previous target:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape :torch.Size([9])
new tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
new shape:torch.Size([1, 9])


In [20]:
#torch permute-rearranges  the dimensions of a target tensor in a specified order
x_original=torch.rand(size=(224,224,3))#[height,width,colour_channel]

#permute the orginial tensor to rearrange the axis (or dim) order
x_permute=x_original.permute(2,0,1)#shift axis 0->1,1->2,2->0

print(f"previous shape:{x_original.shape}")
print(f"new shape:{x_permute.shape}")#[colout_channel,height,width]

previous shape:torch.Size([224, 224, 3])
new shape:torch.Size([3, 224, 224])
