Indexing(selecting data from tensors)

In [1]:
#indexing with pytorch is similar to indexing with numpy
import torch
import pandas as pd 
import numpy as np

In [2]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [3]:
#let index on new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
#let's index on middle bracket
x[0,0]
x[0][0]

tensor([1, 2, 3])

In [8]:
#let's index on inner bracket
x[0][0][2]

tensor(3)

In [10]:
#you can also use ":" to select "all" of a target dimension
x[:,0]
x[:,1]

tensor([[4, 5, 6]])

In [11]:
#get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [12]:
#get all values of the 0 dimesnions but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [13]:
#get index 0 of oth and 1st dimension and all values of 2nd dimension
x[0,0,:]


tensor([1, 2, 3])

In [14]:
#index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

Pytorch tensors and numpy

In [18]:
#numpy array to tensor
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)#warning:when converting from numpy->pytorch reflect numpy's default numpy datatype of float64 unless specified otherwise
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [19]:
#change the value of array,what will this do to tensor?
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [20]:
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [21]:
numpy_tensor.dtype

dtype('float32')

In [22]:
#change the tensor,what happens to 'numpy_tensor'?
tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))