Reproducebility(trying to take random out of random)

In [1]:
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

Looking in indexes: https://download.pytorch.org/whl/cu121
Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch

In [3]:
torch.rand(3,3)

tensor([[0.5124, 0.5708, 0.6516],
        [0.8215, 0.8705, 0.1857],
        [0.4751, 0.0050, 0.0850]])

In [5]:
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.6874, 0.4255, 0.3739, 0.7307],
        [0.1003, 0.2292, 0.2217, 0.0333],
        [0.6391, 0.4840, 0.2701, 0.6850]])
tensor([[0.9215, 0.3686, 0.1369, 0.9219],
        [0.2985, 0.2306, 0.1991, 0.4513],
        [0.7172, 0.4040, 0.9115, 0.7905]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [6]:
#let's make some random but reproducible tensors

RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)

random_tensor_C=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D=torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Running Tensorss and pytorch objects on the GPU's

In [7]:
#getting a GPU
!nvidia-smi

Sat Mar 21 10:51:56 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 576.93                 Driver Version: 576.93         CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   47C    P0             13W /   30W |       0MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [8]:
#check for gpu access
torch.cuda.is_available()

True

In [9]:
#setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device


'cuda'

In [10]:
#count number of devices
torch.cuda.device_count()

1

In [11]:
#create a tensor (default ont the cpu)
tensor=torch.tensor([1,2,3])

#tensor not on GPU
print(tensor,tensor.device)


tensor([1, 2, 3]) cpu


In [12]:
#move tensor on GPU (if available)

tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [14]:
#to fix the GPU with numpy issue,we can first set it to the cpu
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()

In [ ]:
#exercise & extra-curiculum
