In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch

In [3]:
random_tensor_image=torch.rand(size=(223,223,3))

random_tensor_image.shape,random_tensor_image.ndim

(torch.Size([223, 223, 3]), 3)

In [4]:
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
ten_zeros=torch.zeros_like(torch.arange(1,22))
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.9446, 0.5915, 0.9865, 0.9540],
        [0.4074, 0.4436, 0.2287, 0.8373],
        [0.9344, 0.6598, 0.6427, 0.1170]])

In [13]:
print(f"datatype:{some_tensor.dtype}")
print(f"device:{some_tensor.device}")

datatype:torch.float32
device:cpu


In [16]:
tensor=torch.tensor([1,2,3])
torch.mul(tensor,10)

tensor([10, 20, 30])

In [18]:
tensor_A=torch.tensor([[1,2,3],
                     [4,5,6]])
tensor_B=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

torch.matmul(tensor_A,tensor_B)

tensor([[22, 28],
        [49, 64]])

In [19]:
x=torch.arange(1,22,1)
torch.min(x)

tensor(1)

In [20]:
torch.max(x)

tensor(21)

In [22]:
torch.mean(x.type(torch.float32))

tensor(11.)

In [23]:
torch.argmax(x)

tensor(20)

In [27]:
x=torch.arange(1.,11.)
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [30]:
x_reshaped=x.reshape(1,10)
x_reshaped

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])